### ISSUE TITLE
ValueError: not enough values to unpack (expected 7, got 0)

### ISSUE THREAD

**Issue by shxzhao** [WeijingShi/Point-GNN#87]
When I retrain the model without the Pre training model，this error occurred ! I want to know how to solve it, can you give me some advice. Looking forward to your reply.

Traceback (most recent call last):
  File "/home/rtx-3090/anaconda3/envs/tensorflow/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/rtx-3090/PycharmProjects/Point-GNN-master/Point-GNN/train.py", line 85, in fetch_data
    cam_rgb_points, box_label_list = aug_fn(cam_rgb_points, box_label_list)
  File "/home/rtx-3090/PycharmProjects/Point-GNN-master/Point-GNN/models/preprocess.py", line 468, in multiple_aug
    cam_rgb_points, labels, **aug_config['method_kwargs'])
  File "/home/rtx-3090/PycharmProjects/Point-GNN-master/Point-GNN/models/preprocess.py", line 301, in random_box_shift
    appr_factor*boxes_3d_to_corners(label_boxes))
  File "/home/rtx-3090/PycharmProjects/Point-GNN-master/Point-GNN/models/nms.py", line 35, in boxes_3d_to_corners
    x3d, y3d, z3d, l, h, w, yaw = box_3d
ValueError: not enough values to unpack (expected 7, got 0)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rtx-3090/PycharmProjects/Point-GNN-master/Point-GNN/train.py", line 542, in <module>
    = data_provider.provide_batch(batch_frame_idx_list)
  File "/home/rtx-3090/PycharmProjects/Point-GNN-master/Point-GNN/train.py", line 482, in provide_batch
    batch_list.append(self.provide(frame_idx))
  File "/home/rtx-3090/PycharmProjects/Point-GNN-master/Point-GNN/train.py", line 475, in provide
    return self.async_load(frame_idx)
  File "/home/rtx-3090/PycharmProjects/Point-GNN-master/Point-GNN/train.py", line 447, in async_load
    data = self._results[frame_idx].get()
  File "/home/rtx-3090/anaconda3/envs/tensorflow/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
ValueError: not enough values to unpack (expected 7, got 0)

**Comment by WeijingShi** [comment]
Hi @shxzhao, 

Thanks for your interest in our work. 

It seems one of your label_boxes is empty. But the label_boxes should not have empty boxes as it is generated by:
https://github.com/WeijingShi/Point-GNN/blob/48f3d79d5b101d3a4b8439ba74c92fcad4f7cab0/models/preprocess.py#L296
label_boxes should be either empty or an N by 7 arrays. 

Did you modify the code or dataset? 

Thanks,
