### ISSUE TITLE
i have finish Prerequisites and no error , however when i run run.py , python report SyntaxError: invalid syntax 

### ISSUE THREAD

**Issue by miaozujia** [WeijingShi/Point-GNN#94]
my environment:
# conda list
-------------------------------------------------------------------------------------------------------------------------------------
(pointgnn) siat@siat-Precision-3640-Tower:~/work/machine_learning/Point-GNN-master$ conda list
 packages in environment at /home/siat/Downloads/ENTER/envs/pointgnn:

 Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
_openmp_mutex             5.1                       1_gnu    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ca-certificates           2022.07.19           h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
certifi                   2020.6.20          pyhd3eb1b0_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cycler                    0.10.0                   pypi_0    pypi
kiwisolver                1.1.0                    pypi_0    pypi
libffi                    3.3                  he6710b0_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgcc-ng                 11.2.0               h1234567_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgomp                   11.2.0               h1234567_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libstdcxx-ng              11.2.0               h1234567_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
matplotlib                3.0.3                    pypi_0    pypi
ncurses                   6.3                  h5eee18b_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
open3d                    0.10.0.0                 pypi_0    pypi
openssl                   1.1.1q               h7f8727e_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pip                       20.3.4                   pypi_0    pypi
protobuf                  3.17.3                   pypi_0    pypi
python                    3.5.6                h12debd9_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
readline                  8.1.2                h7f8727e_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
setuptools                50.3.2                   pypi_0    pypi
sqlite                    3.39.2               h5082296_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tk                        8.6.12               h1ccaba5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
wheel                     0.37.1             pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
xz                        5.2.5                h7f8727e_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
zlib                      1.2.12               h7f8727e_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main

# 2, pip list
(pointgnn) siat@siat-Precision-3640-Tower:~/work/machine_learning/Point-GNN-master$ pip list
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Package                       Version
----------------------------- ------------
absl-py                       0.15.0
actionlib                     1.12.1
angles                        1.9.12
argon2-cffi                   21.1.0
astor                         0.8.1
attrs                         22.1.0
backcall                      0.2.0
bleach                        3.3.1
bondpy                        1.8.5
camera-calibration            1.15.0
camera-calibration-parsers    1.11.13
catkin                        0.7.29
certifi                       2020.6.20
cffi                          1.15.1
controller-manager            0.18.4
controller-manager-msgs       0.18.4
cv-bridge                     1.13.0
cycler                        0.10.0
decorator                     5.1.1
defusedxml                    0.7.1
diagnostic-analysis           1.9.7
diagnostic-common-diagnostics 1.9.7
diagnostic-updater            1.9.7
dynamic-reconfigure           1.6.5
entrypoints                   0.3
gast                          0.2.2
gazebo-plugins                2.8.7
gazebo-ros                    2.8.7
gencpp                        0.6.5
geneus                        2.2.6
genlisp                       0.4.16
genmsg                        0.5.16
gennodejs                     2.0.1
genpy                         0.6.16
geodesy                       0.5.3
google-pasta                  0.2.0
grpcio                        1.41.1
h5py                          2.10.0
image-geometry                1.13.0
importlib-metadata            2.1.3
importlib-resources           3.2.1
interactive-markers           1.11.5
ipykernel                     5.5.6
ipython                       7.9.0
ipython-genutils              0.2.0
ipywidgets                    7.7.2
jedi                          0.17.2
Jinja2                        2.11.3
joblib                        0.14.1
joint-state-publisher         1.12.15
jsonschema                    4.0.0
jupyter-client                6.1.13
jupyter-core                  4.6.3
kdl-parser-py                 1.13.3
Keras-Applications            1.0.8
Keras-Preprocessing           1.1.2
kiwisolver                    1.1.0
laser-geometry                1.6.7
Markdown                      3.2.2
MarkupSafe                    1.1.1
matplotlib                    3.0.3
message-filters               1.14.13
mistune                       0.8.4
nbconvert                     5.6.1
nbformat                      5.1.3
nest-asyncio                  1.5.5
notebook                      6.2.0
numpy                         1.18.5
open3d-python                 0.7.0.0
opt-einsum                    3.3.0
packaging                     20.9
pandocfilters                 1.5.0
parso                         0.7.1
pexpect                       4.8.0
pickleshare                   0.7.5
pip                           20.3.4
prometheus-client             0.12.0
prompt-toolkit                2.0.10
protobuf                      3.17.3
ptyprocess                    0.7.0
pycparser                     2.21
Pygments                      2.11.2
pyparsing                     2.4.7
pyrsistent                    0.17.3
python-dateutil               2.8.2
python-qt-binding             0.4.4
pyzmq                         20.0.0
qt-dotgraph                   0.4.2
qt-gui                        0.4.2
qt-gui-cpp                    0.4.2
qt-gui-py-common              0.4.2
resource-retriever            1.12.7
rosbag                        1.14.13
rosboost-cfg                  1.14.9
rosclean                      1.14.9
roscreate                     1.14.9
rosgraph                      1.14.13
roslaunch                     1.14.13
roslib                        1.14.9
roslint                       0.11.2
roslz4                        1.14.13
rosmake                       1.14.9
rosmaster                     1.14.13
rosmsg                        1.14.13
rosnode                       1.14.13
rosparam                      1.14.13
rospy                         1.14.13
rosservice                    1.14.13
rostest                       1.14.13
rostopic                      1.14.13
rosunit                       1.14.9
roswtf                        1.14.13
rqt-action                    0.4.9
rqt-bag                       0.5.1
rqt-bag-plugins               0.5.1
rqt-console                   0.4.9
rqt-dep                       0.4.9
rqt-graph                     0.4.11
rqt-gui                       0.5.3
rqt-gui-py                    0.5.3
rqt-image-view                0.4.16
rqt-launch                    0.4.8
rqt-logger-level              0.4.8
rqt-moveit                    0.5.10
rqt-msg                       0.4.8
rqt-nav-view                  0.5.7
rqt-plot                      0.4.13
rqt-pose-view                 0.5.8
rqt-publisher                 0.4.8
rqt-py-common                 0.5.3
rqt-py-console                0.4.8
rqt-reconfigure               0.5.4
rqt-robot-dashboard           0.5.7
rqt-robot-monitor             0.5.14
rqt-robot-steering            0.5.10
rqt-runtime-monitor           0.5.7
rqt-rviz                      0.7.0
rqt-service-caller            0.4.8
rqt-shell                     0.4.9
rqt-srv                       0.4.8
rqt-tf-tree                   0.6.0
rqt-top                       0.4.8
rqt-topic                     0.4.11
rqt-web                       0.4.8
rviz                          1.13.25
scikit-learn                  0.22.2.post1
scipy                         1.4.1
Send2Trash                    1.8.0
sensor-msgs                   1.12.8
setuptools                    50.3.2
Shapely                       1.7.1
six                           1.16.0
smach                         2.0.1
smach-ros                     2.0.1
smclib                        1.8.5
tensorboard                   1.15.0
tensorflow                    1.15.0
tensorflow-estimator          1.15.1
tensorflow-gpu                1.15.0
termcolor                     1.1.0
terminado                     0.13.0
testpath                      0.6.0
tf                            1.12.1
tf-conversions                1.12.1
tf2-geometry-msgs             0.6.5
tf2-kdl                       0.6.5
tf2-py                        0.6.5
tf2-ros                       0.6.5
topic-tools                   1.14.13
tornado                       6.1
tqdm                          4.64.0
traitlets                     4.3.3
unique-id                     1.0.6
urdfdom-py                    0.4.6
wcwidth                       0.2.5
webencodings                  0.5.1
Werkzeug                      1.0.1
wheel                         0.37.1
widgetsnbextension            3.6.1
wrapt                         1.14.1
xacro                         1.13.17
zipp                          1.2.0

# 3,run.py error
-----------------------------------------------------------------------------------------------------------------------------------------------
(pointgnn) siat@siat-Precision-3640-Tower:~/work/machine_learning/Point-GNN-master$ python run.py checkpoints/car_auto_T3_train/ --dataset_root_dir dataset --output_dir output/
Traceback (most recent call last):
  File "run.py", line 11, in <module>
    import open3d
  File "/home/siat/.local/lib/python3.5/site-packages/open3d/__init__.py", line 52, in <module>
    from open3d.j_visualizer import *
  File "/home/siat/.local/lib/python3.5/site-packages/open3d/j_visualizer.py", line 27, in <module>
    import ipywidgets as widgets
  File "/home/siat/.local/lib/python3.5/site-packages/ipywidgets/__init__.py", line 25, in <module>
    from .widgets import *
  File "/home/siat/.local/lib/python3.5/site-packages/ipywidgets/widgets/__init__.py", line 4, in <module>
    from .widget import Widget, CallbackDispatcher, register, widget_serialization
  File "/home/siat/.local/lib/python3.5/site-packages/ipywidgets/widgets/widget.py", line 19, in <module>
    from ipykernel.comm import Comm
  File "/home/siat/.local/lib/python3.5/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/home/siat/.local/lib/python3.5/site-packages/ipykernel/connect.py", line 16, in <module>
    import jupyter_client
  File "/home/siat/.local/lib/python3.5/site-packages/jupyter_client/__init__.py", line 6, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "/home/siat/.local/lib/python3.5/site-packages/jupyter_client/asynchronous/__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "/home/siat/.local/lib/python3.5/site-packages/jupyter_client/asynchronous/client.py", line 6, in <module>
    from jupyter_client.channels import HBChannel
  File "/home/siat/.local/lib/python3.5/site-packages/jupyter_client/channels.py", line 47
    time_to_dead: float = 1.0
                ^
SyntaxError: invalid syntax

**Comment by louzhenghao** [comment]
There may be a version problem with your open3d
